//HintName: CakeConstants.g.cs

/// <summary>
/// Contains constants generated by Cake.Generator.Core.
/// </summary>
public static partial class Program
{
    /// <summary>
    /// The version of Cake.Generator.Core used to generate these aliases.
    /// </summary>
    public const string CakeGeneratorDate = "2025-06-07 17:28:44Z";
    public const string CakeGeneratorVersion = "5.0.25158.20967";
    public const string CakeGeneratorInformationalVersion = "5.0.25158.20967-local+e5616adddc7809416d304d094c97aced16dcd1a9";
    public const string CakeGeneratorNuGetVersion = "5.0.25158.20967-local";
}